/**
 * Deterministic canonical HCL materialization: `hcl.canonical-document@1`
 * (RFC 0014 §9).
 *
 * authority:
 *  - RFC 0004 §3 (:57-94) the common MaterializationRequest; §7 (:170-192)
 *    the completion algebra
 *  - RFC 0014 §9 (:574-629): the canonical style — UTF-8 without BOM, LF
 *    line endings, two-space indentation, `name = value` attributes, block
 *    headers as `type "label" {`, a trailing newline after the final item,
 *    minimal deterministic string escapes, canonical decimal spellings,
 *    one-item-per-line tuples and objects with `=` keys, `hcl.expression@1`
 *    records emitting their canonical text, labels always quoted; the two
 *    value spellings (raw typed member or value record with a string
 *    `kind` member); the tfvars profile rejects any record containing a
 *    block; every style validates, encodes, reparses the exact generated
 *    bytes, and compares the reparsed native model to the promised input
 *    semantics — failure returns no target Document, partial bytes, or
 *    partial provenance
 *  - crates/consema-hcl/src/materialization.rs — validate_request :266-285
 *    (only `hcl.native@1`/`hcl.tfvars@1` + the canonical style + UTF-8 +
 *    Lf), the parse limits for the closure reparse :295-328, write_body
 *    :1174-1208, write_value :1211-1253, write_object_key :1255-1264
 *    (bare identifier except `for`), is_plain_identifier :1266-1278,
 *    escape_text :1296-1333 (the `$`/`%` run doubling), render_decimal
 *    :1344-1366, verify_closure :1773-1860 (lockstep comparison by
 *    canonical-decimal equality and structural equality)
 *
 * Design (TypeScript-idiomatic): the input record is a plain JS value
 * tree in either pinned spelling, normalized once into a closed ValueNode
 * tree (any deviation is InvalidRequest "invalid-record"); a bounded byte
 * writer mirrors the Rust writer; the result is the sealed RFC 0004 §7
 * union from the document domain. The reparse closure re-forms the exact
 * generated bytes and walks the input record and the reparsed body in
 * lockstep, comparing numbers by canonical-decimal value equality and
 * everything else structurally (RFC 0014 §6).
 */

import {
  MaterializationRequest,
  MaterializationReport,
  FailedMaterializationAttempt,
  CompleteMaterialization,
  MaterializationProvenanceEntry,
  MaterializationProvenanceMap,
  MaterializedOrigin,
} from '../document/materialization.ts';
import type {
  MaterializationFidelity,
  MaterializationLimits,
  MaterializationResult,
} from '../document/materialization.ts';
import { MaterializationFailure } from '../document/errors.ts';
import { ValuePath } from '../document/portable_locations.ts';
import { HclAttribute, HclBlock } from './document.ts';
import type { HclDocument } from './document.ts';
import { HclProfile } from './profile.ts';
import { parseHcl, profileDefaultEncoding } from './document.ts';
import type { HclParseLimits } from './limits.ts';
import { hclParseLimits } from './limits.ts';
import {
  isLiteralComplete,
  literalValue,
  expressionKindOf,
  kindFamily,
  expressionFingerprint,
} from './expression.ts';

// ---------------------------------------------------------------------------
// Input record spellings (RFC 0014 §9)
// ---------------------------------------------------------------------------

/** The `hcl.expression@1` record spelling. */
export interface HclExpressionRecordInput {
  readonly record: 'hcl.expression@1';
  readonly kind: string;
  readonly text: string;
  readonly fingerprint?: string;
}

/** One attribute value in either pinned spelling (RFC 0014 §9). */
export type HclValueInput =
  | { readonly kind: 'string'; readonly text: string }
  | { readonly kind: 'integer'; readonly value: number | bigint }
  | { readonly kind: 'real'; readonly value: number }
  | { readonly kind: 'boolean'; readonly value: boolean }
  | { readonly kind: 'null' }
  | { readonly kind: 'tuple'; readonly elements: readonly HclValueInput[] }
  | { readonly kind: 'object'; readonly entries: readonly (readonly [string, HclValueInput])[] }
  | { readonly kind: 'expression'; readonly expression: HclExpressionRecordInput }
  | string
  | number
  | boolean
  | null
  | readonly HclValueInput[]
  | readonly (readonly [string, HclValueInput])[];

/** One `hcl.body@1` record in the pinned spelling. */
export interface HclBodyRecordInput {
  readonly record: 'hcl.body@1';
  readonly items: readonly HclBodyItemInput[];
}

/** One body item in the pinned spelling. */
export type HclBodyItemInput =
  | {
      readonly kind: 'attribute';
      readonly name: string;
      readonly value: HclValueInput;
    }
  | {
      readonly kind: 'block';
      readonly type: string;
      readonly labels: readonly string[];
      readonly body: HclBodyRecordInput;
    };

// ---------------------------------------------------------------------------
// Normalized value tree
// ---------------------------------------------------------------------------

type ValueNode =
  | { readonly kind: 'String'; readonly text: string }
  | { readonly kind: 'Integer'; readonly canonical: string }
  | { readonly kind: 'Real'; readonly canonical: string }
  | { readonly kind: 'Boolean'; readonly value: boolean }
  | { readonly kind: 'Null' }
  | { readonly kind: 'Tuple'; readonly elements: readonly ValueNode[] }
  | { readonly kind: 'Object'; readonly entries: readonly { readonly key: string; readonly value: ValueNode }[] }
  | { readonly kind: 'Expression'; readonly kindName: string; readonly text: string; readonly fingerprint: string | null };

interface NormalizedBody {
  readonly items: readonly NormalizedItem[];
}

type NormalizedItem =
  | { readonly kind: 'attribute'; readonly name: string; readonly value: ValueNode }
  | {
      readonly kind: 'block';
      readonly type: string;
      readonly labels: readonly string[];
      readonly body: NormalizedBody;
    };

/** A record is an ordered entry-mapping object only when every element is a `[string, value]` pair. */
function isEntryPair(value: unknown): value is readonly [string, unknown] {
  return (
    Array.isArray(value) &&
    value.length === 2 &&
    typeof value[0] === 'string'
  );
}

function invalidRecord(reason: string): MaterializationFailure {
  return new MaterializationFailure('InvalidRequest', { reason });
}

/**
 * Normalizes one body record; any deviation is InvalidRequest "invalid-record".
 *
 * The `record: "hcl.body@1"` discriminator is required at the top level only
 * (materialization.rs:380-402). A block item's nested body is validated by
 * `Body::validate` (:522-543), which reads only the `items` member, so the
 * published vector spelling `{ "items": [...] }` without the discriminator
 * is accepted at nested levels (hcl-v1.json canonical-document block item).
 */
function normalizeBody(record: unknown, topLevel: boolean): NormalizedBody {
  if (typeof record !== 'object' || record === null || Array.isArray(record)) {
    throw invalidRecord('body-record');
  }
  const body = record as Record<string, unknown>;
  if (topLevel && body.record !== 'hcl.body@1') {
    throw invalidRecord('body-record');
  }
  if (!Array.isArray(body.items)) {
    throw invalidRecord('body-items');
  }
  const items: NormalizedItem[] = [];
  for (const item of body.items) {
    if (typeof item !== 'object' || item === null || Array.isArray(item)) {
      throw invalidRecord('body-item');
    }
    const itemRecord = item as Record<string, unknown>;
    const kind = itemRecord.kind;
    if (kind === 'attribute') {
      if (typeof itemRecord.name !== 'string' || itemRecord.value === undefined) {
        throw invalidRecord('attribute-item');
      }
      items.push({ kind: 'attribute', name: itemRecord.name, value: normalizeValue(itemRecord.value) });
    } else if (kind === 'block') {
      if (
        typeof itemRecord.type !== 'string' ||
        !Array.isArray(itemRecord.labels) ||
        !itemRecord.labels.every((label) => typeof label === 'string') ||
        itemRecord.body === undefined
      ) {
        throw invalidRecord('block-item');
      }
      items.push({
        kind: 'block',
        type: itemRecord.type,
        labels: itemRecord.labels as string[],
        body: normalizeBody(itemRecord.body, false),
      });
    } else {
      throw invalidRecord('body-item');
    }
  }
  return { items };
}

/** Normalizes one attribute value in either spelling (RFC 0014 §9). */
export function normalizeValue(value: unknown): ValueNode {
  if (typeof value === 'string') {
    return { kind: 'String', text: value };
  }
  if (typeof value === 'number') {
    if (Number.isInteger(value)) {
      return { kind: 'Integer', canonical: BigInt(value).toString() };
    }
    return { kind: 'Real', canonical: canonicalRealFromNumber(value) };
  }
  if (typeof value === 'boolean') {
    return { kind: 'Boolean', value };
  }
  if (value === null) {
    return { kind: 'Null' };
  }
  if (Array.isArray(value)) {
    if (value.length > 0 && value.every(isEntryPair)) {
      const entries = value.map(([key, entryValue]) => ({
        key,
        value: normalizeValue(entryValue),
      }));
      return { kind: 'Object', entries };
    }
    const elements = value.map((element) => normalizeValue(element));
    return { kind: 'Tuple', elements };
  }
  if (typeof value === 'object') {
    const record = value as Record<string, unknown>;
    switch (record.kind) {
      case 'string':
        if (typeof record.text !== 'string') {
          throw invalidRecord('string-record');
        }
        return { kind: 'String', text: record.text };
      case 'integer':
        if (typeof record.value !== 'number' && typeof record.value !== 'bigint') {
          throw invalidRecord('integer-record');
        }
        if (typeof record.value === 'number' && !Number.isInteger(record.value)) {
          throw invalidRecord('integer-record');
        }
        return { kind: 'Integer', canonical: BigInt(record.value).toString() };
      case 'real':
        if (typeof record.value !== 'number' || !Number.isFinite(record.value)) {
          throw invalidRecord('real-record');
        }
        return { kind: 'Real', canonical: canonicalRealFromNumber(record.value) };
      case 'boolean':
        if (typeof record.value !== 'boolean') {
          throw invalidRecord('boolean-record');
        }
        return { kind: 'Boolean', value: record.value };
      case 'null':
        return { kind: 'Null' };
      case 'tuple': {
        if (!Array.isArray(record.elements)) {
          throw invalidRecord('tuple-record');
        }
        return { kind: 'Tuple', elements: record.elements.map((element) => normalizeValue(element)) };
      }
      case 'object': {
        if (!Array.isArray(record.entries) || !record.entries.every(isEntryPair)) {
          throw invalidRecord('object-record');
        }
        return {
          kind: 'Object',
          entries: record.entries.map(([key, entryValue]) => ({
            key,
            value: normalizeValue(entryValue),
          })),
        };
      }
      case 'expression': {
        const expression = record.expression as Record<string, unknown> | undefined;
        if (
          typeof expression !== 'object' ||
          expression === null ||
          expression.record !== 'hcl.expression@1' ||
          typeof expression.kind !== 'string' ||
          typeof expression.text !== 'string'
        ) {
          throw invalidRecord('expression-record');
        }
        const fingerprint = expression.fingerprint;
        if (fingerprint !== undefined && typeof fingerprint !== 'string') {
          throw invalidRecord('expression-record');
        }
        return {
          kind: 'Expression',
          kindName: expression.kind,
          text: expression.text,
          fingerprint: typeof fingerprint === 'string' ? fingerprint : null,
        };
      }
      default:
        throw invalidRecord('value-record');
    }
  }
  throw invalidRecord('value-record');
}

/** The canonical decimal spelling of one finite JS number (shortest round-trip). */
export function canonicalRealFromNumber(value: number): string {
  if (value === 0) {
    return '0';
  }
  const text = String(value);
  const exponentIndex = text.search(/[eE]/);
  if (exponentIndex < 0) {
    return text;
  }
  // Fold the exponent into the decimal point position.
  const mantissa = text.slice(0, exponentIndex);
  const exponent = Number(text.slice(exponentIndex + 1));
  const negative = mantissa.startsWith('-');
  const unsigned = negative ? mantissa.slice(1) : mantissa;
  const dot = unsigned.indexOf('.');
  const digits = unsigned.replace('.', '');
  const point = (dot < 0 ? digits.length : dot) + exponent;
  let out: string;
  if (point <= 0) {
    out = `0.${'0'.repeat(-point)}${digits}`;
  } else if (point >= digits.length) {
    out = digits + '0'.repeat(point - digits.length);
  } else {
    out = `${digits.slice(0, point)}.${digits.slice(point)}`;
  }
  if (negative) {
    out = `-${out}`;
  }
  return out;
}

// ---------------------------------------------------------------------------
// The canonical writer (materialization.rs:1140-1366)
// ---------------------------------------------------------------------------

class Writer {
  readonly #limits: MaterializationLimits;
  #out = '';

  constructor(limits: MaterializationLimits) {
    this.#limits = limits;
  }

  push(text: string): void {
    const next = this.#out.length + text.length;
    if (next > this.#limits.maxOutputBytes) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'output-bytes' });
    }
    this.#out += text;
  }

  indent(depth: number): void {
    for (let i = 0; i < depth; i++) {
      this.push('  ');
    }
  }

  pushQuoted(text: string): void {
    this.push('"');
    this.push(escapeText(text));
    this.push('"');
  }

  finish(): string {
    return this.#out;
  }
}

/** Escapes one string with the minimal deterministic escape set (materialization.rs:1296-1333). */
export function escapeText(text: string): string {
  let out = '';
  let index = 0;
  while (index < text.length) {
    const byte = text.charCodeAt(index);
    if (byte === 0x24 || byte === 0x25) {
      let run = 1;
      while (index + run < text.length && text.charCodeAt(index + run) === byte) {
        run += 1;
      }
      const doubled = index + run < text.length && text.charCodeAt(index + run) === 0x7b;
      for (let i = 0; i < run + (doubled ? 1 : 0); i++) {
        out += String.fromCharCode(byte);
      }
      index += run;
    } else {
      const character = text[index];
      switch (character) {
        case '"':
          out += '\\"';
          break;
        case '\\':
          out += '\\\\';
          break;
        case '\n':
          out += '\\n';
          break;
        case '\r':
          out += '\\r';
          break;
        case '\t':
          out += '\\t';
          break;
        default: {
          const codePoint = text.codePointAt(index)!;
          if (isEscapedControl(codePoint)) {
            out += `\\u${codePoint.toString(16).padStart(4, '0')}`;
          } else {
            out += character;
          }
          break;
        }
      }
      index += character.length;
    }
  }
  return out;
}

/** C0 controls other than the named escapes, DEL, and the C1 controls (materialization.rs:1280-1286). */
function isEscapedControl(value: number): boolean {
  return value < 0x20 || (value >= 0x7f && value <= 0x9f);
}

/** Whether one text is a valid UAX #31 identifier with the frozen hyphen continuation (materialization.rs:1266-1278). */
function isPlainIdentifier(text: string): boolean {
  if (text.length === 0) {
    return false;
  }
  const first = text.codePointAt(0)!;
  const firstChar = String.fromCodePoint(first);
  if (firstChar === '_' || !/^\p{ID_Start}$/u.test(firstChar)) {
    return false;
  }
  let index = firstChar.length;
  while (index < text.length) {
    const char = text[index];
    if (!/^\p{ID_Continue}$/u.test(char) && char !== '-') {
      return false;
    }
    index += char.length;
  }
  return true;
}

function writeBody(writer: Writer, body: NormalizedBody, depth: number): void {
  for (const item of body.items) {
    if (item.kind === 'attribute') {
      writer.indent(depth);
      writer.push(item.name);
      writer.push(' = ');
      writeValue(writer, item.value, depth);
      writer.push('\n');
    } else {
      writer.indent(depth);
      writer.push(item.type);
      for (const label of item.labels) {
        writer.push(' ');
        writer.pushQuoted(label);
      }
      writer.push(' {\n');
      writeBody(writer, item.body, depth + 1);
      writer.indent(depth);
      writer.push('}\n');
    }
  }
}

function writeValue(writer: Writer, value: ValueNode, depth: number): void {
  switch (value.kind) {
    case 'String':
      writer.pushQuoted(value.text);
      break;
    case 'Integer':
    case 'Real':
      writer.push(value.canonical);
      break;
    case 'Boolean':
      writer.push(value.value ? 'true' : 'false');
      break;
    case 'Null':
      writer.push('null');
      break;
    case 'Tuple': {
      if (value.elements.length === 0) {
        writer.push('[]');
        return;
      }
      writer.push('[\n');
      const last = value.elements.length - 1;
      for (let index = 0; index < value.elements.length; index++) {
        writer.indent(depth + 1);
        writeValue(writer, value.elements[index], depth + 1);
        writer.push(index === last ? '\n' : ',\n');
      }
      writer.indent(depth);
      writer.push(']');
      break;
    }
    case 'Object': {
      if (value.entries.length === 0) {
        writer.push('{}');
        return;
      }
      writer.push('{\n');
      const last = value.entries.length - 1;
      for (let index = 0; index < value.entries.length; index++) {
        writer.indent(depth + 1);
        writeObjectKey(writer, value.entries[index].key);
        writer.push(' = ');
        writeValue(writer, value.entries[index].value, depth + 1);
        writer.push(index === last ? '\n' : ',\n');
      }
      writer.indent(depth);
      writer.push('}');
      break;
    }
    case 'Expression':
      writer.push(value.text);
      break;
  }
}

function writeObjectKey(writer: Writer, key: string): void {
  if (isPlainIdentifier(key) && key !== 'for') {
    writer.push(key);
  } else {
    writer.pushQuoted(key);
  }
}

// ---------------------------------------------------------------------------
// Closure verification (materialization.rs:1773-1860)
// ---------------------------------------------------------------------------

/** Compares the reparsed native model to the promised input semantics (RFC 0014 §9). */
function verifyClosure(
  body: NormalizedBody,
  document: HclDocument,
  limits: MaterializationLimits,
): MaterializationProvenanceMap {
  const entries: MaterializationProvenanceEntry[] = [];
  let units = 0;
  const note = (entry: MaterializationProvenanceEntry): void => {
    units += 1 + entry.outputs().length;
    if (units > limits.maxProvenanceEntries) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'provenance-entries' });
    }
    entries.push(entry);
  };
  verifyBody(body, document.root(), document, ValuePath.root(), note);
  return MaterializationProvenanceMap.create(entries, document.snapshotIdentity(), limits);
}

function verifyBody(
  body: NormalizedBody,
  nativeBody: import('./document.ts').HclBody,
  document: HclDocument,
  path: ValuePath,
  note: (entry: MaterializationProvenanceEntry) => void,
): void {
  const nativeItems = nativeBody.items();
  if (nativeItems.length !== body.items.length) {
    throw new MaterializationFailure('FormationFailed');
  }
  for (let index = 0; index < body.items.length; index++) {
    const promised = body.items[index];
    const native = nativeItems[index];
    const itemPath = path.child({ kind: 'SequenceElement', index: BigInt(index) });
    if (promised.kind === 'attribute') {
      if (!(native instanceof HclAttribute)) {
        throw new MaterializationFailure('FormationFailed');
      }
      if (native.name() !== promised.name) {
        throw new MaterializationFailure('FormationFailed');
      }
      const valuePath = itemPath.child({ kind: 'ObjectValue', name: 'value' });
      verifyValue(promised.value, native.expression(), document, valuePath, note);
    } else {
      if (!(native instanceof HclBlock)) {
        throw new MaterializationFailure('FormationFailed');
      }
      if (native.type() !== promised.type) {
        throw new MaterializationFailure('FormationFailed');
      }
      const nativeLabels = native.labels();
      if (nativeLabels.length !== promised.labels.length) {
        throw new MaterializationFailure('FormationFailed');
      }
      for (let labelIndex = 0; labelIndex < promised.labels.length; labelIndex++) {
        if (nativeLabels[labelIndex].text() !== promised.labels[labelIndex]) {
          throw new MaterializationFailure('FormationFailed');
        }
      }
      const bodyPath = itemPath.child({ kind: 'ObjectValue', name: 'body' });
      note(
        new MaterializationProvenanceEntry(
          { kind: 'Value', path: bodyPath },
          [
            new MaterializedOrigin(
              document.snapshotIdentity(),
              native.nodeRef(),
              native.span(),
              'Direct',
            ),
          ],
        ),
      );
      verifyBody(promised.body, native.body(), document, bodyPath, note);
    }
  }
}

function verifyValue(
  promised: ValueNode,
  native: import('./document.ts').HclExpressionHandle,
  document: HclDocument,
  path: ValuePath,
  note: (entry: MaterializationProvenanceEntry) => void,
): void {
  const node = native.node();
  if (promised.kind === 'Expression') {
    if (kindFamily(expressionKindOf(node)) !== promised.kindName) {
      throw new MaterializationFailure('FormationFailed');
    }
    if (native.text() !== promised.text) {
      throw new MaterializationFailure('FormationFailed');
    }
    if (promised.fingerprint !== null) {
      const actual = expressionFingerprint(node).toString(16).padStart(16, '0');
      if (actual !== promised.fingerprint) {
        throw new MaterializationFailure('FormationFailed');
      }
    }
    note(
      new MaterializationProvenanceEntry(
        { kind: 'Value', path },
        [new MaterializedOrigin(document.snapshotIdentity(), native.nodeRef(), native.span(), 'Direct')],
      ),
    );
    return;
  }
  if (!isLiteralComplete(node)) {
    throw new MaterializationFailure('FormationFailed');
  }
  const literal = literalValue(node);
  if (literal === null) {
    throw new MaterializationFailure('FormationFailed');
  }
  const canonical = literalCanonical(literal);
  switch (promised.kind) {
    case 'String':
      if (literal.kind !== 'String' || literal.text !== promised.text) {
        throw new MaterializationFailure('FormationFailed');
      }
      break;
    case 'Integer':
    case 'Real':
      if (canonical !== promised.canonical) {
        throw new MaterializationFailure('FormationFailed');
      }
      break;
    case 'Boolean':
      if (literal.kind !== 'Boolean' || literal.value !== promised.value) {
        throw new MaterializationFailure('FormationFailed');
      }
      break;
    case 'Null':
      if (literal.kind !== 'Null') {
        throw new MaterializationFailure('FormationFailed');
      }
      break;
    case 'Tuple': {
      if (literal.kind !== 'Tuple' || literal.elements.length !== promised.elements.length) {
        throw new MaterializationFailure('FormationFailed');
      }
      for (let index = 0; index < promised.elements.length; index++) {
        if (literalCanonical(literal.elements[index]) !== valueNodeCanonical(promised.elements[index])) {
          throw new MaterializationFailure('FormationFailed');
        }
      }
      break;
    }
    case 'Object': {
      if (literal.kind !== 'Object' || literal.entries.length !== promised.entries.length) {
        throw new MaterializationFailure('FormationFailed');
      }
      for (let index = 0; index < promised.entries.length; index++) {
        const promisedEntry = promised.entries[index];
        const literalEntry = literal.entries[index];
        const literalKey = literalKeyCanonical(literalEntry.key);
        if (literalKey !== promisedEntry.key) {
          throw new MaterializationFailure('FormationFailed');
        }
        if (literalCanonical(literalEntry.value) !== valueNodeCanonical(promisedEntry.value)) {
          throw new MaterializationFailure('FormationFailed');
        }
      }
      break;
    }
  }
  note(
    new MaterializationProvenanceEntry(
      { kind: 'Value', path },
      [new MaterializedOrigin(document.snapshotIdentity(), native.nodeRef(), native.span(), 'Direct')],
    ),
  );
}

/** The canonical encoding of one promised value node (numbers by canonical-decimal equality). */
function valueNodeCanonical(value: ValueNode): string {
  switch (value.kind) {
    case 'String':
      return `s:${value.text}`;
    case 'Integer':
    case 'Real':
      return value.canonical;
    case 'Boolean':
      return `b:${value.value}`;
    case 'Null':
      return 'null';
    case 'Tuple':
      return `[${value.elements.map(valueNodeCanonical).join(',')}]`;
    case 'Object':
      return `{${value.entries
        .map((entry) => `${entry.key}=${valueNodeCanonical(entry.value)}`)
        .join(',')}}`;
    case 'Expression':
      return `e:${value.text}`;
  }
}

/** The canonical-decimal spelling of one literal value (numbers by canonical-decimal equality). */
function literalCanonical(literal: import('./expression.ts').HclLiteralValue): string {
  switch (literal.kind) {
    case 'Integer':
    case 'Decimal':
      return literal.canonical;
    case 'String':
      return `s:${literal.text}`;
    case 'Boolean':
      return `b:${literal.value}`;
    case 'Null':
      return 'null';
    case 'Tuple':
      return `[${literal.elements.map(literalCanonical).join(',')}]`;
    case 'Object':
      return `{${literal.entries
        .map((entry) => `${literalKeyCanonical(entry.key)}=${literalCanonical(entry.value)}`)
        .join(',')}}`;
  }
}

/** The canonical string spelling of one literal key (RFC 0014 §8.2). */
function literalKeyCanonical(key: import('./expression.ts').HclLiteralKey): string {
  switch (key.kind) {
    case 'Identifier':
      return key.name;
    case 'Number':
      return key.canonical;
    case 'String':
      return key.text;
    case 'Value':
      return literalKeyValueCanonical(key.value);
  }
}

function literalKeyValueCanonical(value: import('./expression.ts').HclLiteralValue): string {
  switch (value.kind) {
    case 'String':
      return value.text;
    case 'Integer':
    case 'Decimal':
      return value.canonical;
    case 'Boolean':
      return value.value ? 'true' : 'false';
    case 'Null':
      return 'null';
    case 'Tuple':
    case 'Object':
      throw new MaterializationFailure('FormationFailed');
  }
}

// ---------------------------------------------------------------------------
// Parse limits for the closure reparse (materialization.rs:295-328)
// ---------------------------------------------------------------------------

/** Derived limits so a bounded input cannot fail its own closure. */
export function closureParseLimits(limits: MaterializationLimits): HclParseLimits {
  return hclParseLimits({
    common: {
      maxSourceBytes: limits.maxOutputBytes,
      maxNestingDepth: limits.maxDepth + 2,
      maxTokenCount: limits.maxOutputBytes,
      maxNodeCount: limits.maxOutputBytes,
      maxDiagnostics: limits.maxReportEntries,
    },
    maxDecodedUtf8Bytes: limits.maxOutputBytes * 3,
    maxDecodedScalars: limits.maxOutputBytes,
    maxBodyDepth: limits.maxDepth + 2,
    maxExpressionDepth: limits.maxDepth + 2,
    maxTemplateDepth: limits.maxDepth + 2,
    maxAttributeCount: limits.maxInputNodes,
    maxBlockCount: limits.maxInputNodes,
    maxLabelCount: limits.maxInputNodes,
    maxBodyItemCount: limits.maxInputNodes * 2,
    maxIdentifierLen: limits.maxOutputBytes,
    maxStringLen: limits.maxOutputBytes,
    maxNumberDigits: limits.maxOutputBytes,
    maxTemplateLen: limits.maxOutputBytes,
    maxTemplateInterpolations: limits.maxInputNodes,
    maxHeredocLines: limits.maxOutputBytes,
    maxHeredocBytes: limits.maxOutputBytes,
    maxTupleElements: limits.maxInputNodes,
    maxObjectEntries: limits.maxInputNodes,
    maxForExtent: limits.maxInputNodes,
    maxRecoveryRegions: limits.maxReportEntries,
    maxErrorRegions: limits.maxReportEntries,
    maxSyntaxPieces: limits.maxOutputBytes,
    maxReportEvents: limits.maxReportEntries,
  });
}

// ---------------------------------------------------------------------------
// Materialization entry
// ---------------------------------------------------------------------------

/**
 * Materializes one `hcl.body@1` record into a new canonical HCL document
 * (RFC 0014 §9). Returns the sealed RFC 0004 §7 union; a failed attempt
 * contains no Document and no partial bytes.
 */
export function materializeHcl(
  record: HclBodyRecordInput,
  request: MaterializationRequest,
): MaterializationResult<HclDocument> {
  const analyzed: ValuePath[] = [];
  try {
    const profile = validateRequest(request);
    const limits = request.limits();
    const body = normalizeBody(record, true);
    tfvarsBlockCheck(profile, body);
    countInputNodes(body, limits);
    const writer = new Writer(limits);
    writeBody(writer, body, 0);
    const bytes = new TextEncoder().encode(writer.finish());
    let document: HclDocument;
    try {
      document = parseHcl(bytes, profile, profileDefaultEncoding(), closureParseLimits(limits));
    } catch {
      throw new MaterializationFailure('FormationFailed');
    }
    if (document.formationStatus() !== 'Complete') {
      throw new MaterializationFailure('FormationFailed');
    }
    const provenance = verifyClosure(body, document, limits);
    const report = new MaterializationReport([], limits);
    const fidelity: MaterializationFidelity = 'Exact';
    return {
      kind: 'Complete',
      value: new CompleteMaterialization(document, fidelity, report, provenance),
    };
  } catch (failure) {
    if (!(failure instanceof MaterializationFailure)) {
      throw failure;
    }
    return {
      kind: 'Failed',
      value: new FailedMaterializationAttempt(failure, new MaterializationReport([], request.limits()), analyzed),
    };
  }
}

/** The exact target profile under the frozen style contract (materialization.rs:266-285). */
function validateRequest(request: MaterializationRequest): HclProfile {
  const target = request.targetProfile();
  const style = request.style();
  let profile: HclProfile;
  if (target.id() === 'hcl.native' && target.version() === 1) {
    profile = HclProfile.NATIVE_V1;
  } else if (target.id() === 'hcl.tfvars' && target.version() === 1) {
    profile = HclProfile.TFVARS_V1;
  } else {
    throw new MaterializationFailure('UnsupportedProfile');
  }
  if (style.id() !== 'hcl.canonical-document' || style.version() !== 1) {
    throw new MaterializationFailure('UnsupportedStyle');
  }
  if (request.encoding().kind !== 'Utf8') {
    throw new MaterializationFailure('UnsupportedEncoding');
  }
  if (request.newline() !== 'Lf') {
    throw new MaterializationFailure('UnsupportedNewline');
  }
  return profile;
}

/** Counts input nodes and container depth before any allocation (RFC 0004 §19). */
function countInputNodes(body: NormalizedBody, limits: MaterializationLimits): void {
  const state = { nodes: 0, depth: 0 };
  const walk = (items: readonly NormalizedItem[], depth: number): void => {
    if (depth > limits.maxDepth) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'input-depth' });
    }
    for (const item of items) {
      state.nodes += 1;
      if (state.nodes > limits.maxInputNodes) {
        throw new MaterializationFailure('ResourceLimit', { reason: 'input-nodes' });
      }
      if (item.kind === 'attribute') {
        walkValue(item.value, depth + 1, state, limits);
      } else {
        walk(item.body.items, depth + 1);
      }
    }
  };
  walk(body.items, 0);
}

function walkValue(
  value: ValueNode,
  depth: number,
  state: { nodes: number; depth: number },
  limits: MaterializationLimits,
): void {
  if (depth > limits.maxDepth) {
    throw new MaterializationFailure('ResourceLimit', { reason: 'input-depth' });
  }
  state.nodes += 1;
  if (state.nodes > limits.maxInputNodes) {
    throw new MaterializationFailure('ResourceLimit', { reason: 'input-nodes' });
  }
  if (value.kind === 'Tuple') {
    for (const element of value.elements) {
      walkValue(element, depth + 1, state, limits);
    }
  } else if (value.kind === 'Object') {
    for (const entry of value.entries) {
      state.nodes += 1;
      if (state.nodes > limits.maxInputNodes) {
        throw new MaterializationFailure('ResourceLimit', { reason: 'input-nodes' });
      }
      walkValue(entry.value, depth + 1, state, limits);
    }
  }
}

// The tfvars profile refuses any record containing a block
// (RFC 0014 §5, §9); the failure carries `hcl.materialization.unrepresentable@1`
// through the conformance code mapping (hcl_v1.rs:1621). The check happens
// in normalizeBody's callers: materializeHcl validates the profile target
// first, then rejects blocks under the tfvars profile here.
function tfvarsBlockCheck(profile: HclProfile, body: NormalizedBody): void {
  if (profile === HclProfile.TFVARS_V1 && body.items.some((item) => item.kind === 'block')) {
    throw new MaterializationFailure('Unrepresentable', { reason: 'tfvars-block' });
  }
}
