/**
 * Canonical `plist.xml-canonical@1` / `plist.binary-canonical@1`
 * materialization (RFC 0013 §10).
 *
 * authority: crates/consema-plist/src/materialization.rs
 *  - record contract :10-54 (the `plist.value-tree@1` record; dict as
 *    EntryMapping or Object, array as Sequence, typed leaves; an Object
 *    carrying a `kind` member is rejected :532-539; date leaf Object
 *    {epoch, seconds} :540-580; uid leaf Object {uid} :581-602; hex data
 *    leaf Object {hex} :603-620)
 *  - request contract :56-65, validate_request :236-266 (XML: Utf8+Lf;
 *    binary: Binary+None)
 *  - ValueNode validation :438-655 (Decimal converted to double :665-679)
 *  - XML expressibility :712-868 (UID, Float32, non-canonical NaN,
 *    unpaired-surrogate/non-XML-character strings, negative-zero dates,
 *    whole-second calendar limits; fractional seconds under
 *    TruncateWithReport emit plist.materialization.fractional-date@1
 *    events and flip the fidelity to Transformed :873-888)
 *  - serialize_xml :1098-1369 (exact header spelling, four-space indent,
 *    LF endings, decimal integers, shortest-round-trip reals :1235-1248,
 *    whole-second dates :1269-1275, base64 wrapped at `76 - 8 * depth`
 *    :1338-1369, escapes :1221-1231)
 *  - serialize_binary :1414-1617 (plan_binary :1011-1096 — dict first,
 *    then key objects, then values recursively; identical deduplicable
 *    scalars share one object at first occurrence; write_sized :1549-1559,
 *    integer_width :1586-1591, ref_size_for :1574-1582, uid_width
 *    :1607-1617)
 *  - closure :193-233 (reparse the exact generated bytes, Complete with
 *    native-model equality), provenance :1619-1764
 *  - failure mapping :78-94 (Unrepresentable{Date} ->
 *    plist.materialization.fractional-date@1, Unrepresentable{..} ->
 *    plist.materialization.unrepresentable@1, ResourceLimit ->
 *    plist.materialization.resource-limit@1, the shared kinds keep the
 *    core.materialization.* codes)
 *  - vectors: plist.materialization.xml-canonical-text,
 *    plist.materialization.binary-canonical-hex,
 *    plist.materialization.normalization-and-conversion,
 *    plist.materialization.fractional-date-policy,
 *    plist.materialization.old-record-shape-rejected
 *
 * RECORDED DIVERGENCE RISK (blind-write, L3): real rendering uses JS
 * `Number.toString()` (shortest round-trip); Rust's `f64::to_string`
 * differs only in exponent spellings (JS writes `1e+21`, Rust writes
 * `1e21`) and the vectors exercise neither spelling.
 *
 * Design (TypeScript-idiomatic): validate the complete record, build the
 * promised native document, serialize, reparse the exact generated bytes,
 * and compare the reparsed native model — failure returns no Document,
 * no partial bytes, and no partial provenance.
 */

import {
  CompleteMaterialization,
  FailedMaterializationAttempt,
  MaterializationProvenanceEntry,
  MaterializationProvenanceMap,
  MaterializationReport,
  MaterializationRequest,
  MaterializedOrigin,
} from '../document/materialization.ts';
import type {
  MaterializationFidelity,
  MaterializationLimits,
  MaterializationResult,
} from '../document/materialization.ts';
import { MaterializationFailure } from '../document/errors.ts';
import { diagnostic } from '../document/diagnostic.ts';
import type { Diagnostic } from '../document/diagnostic.ts';
import { Span } from '../document/identity.ts';
import { ValuePath } from '../document/portable_locations.ts';
import type { PortableValue } from '../core/value.ts';
import { parse } from './parser.ts';
import { PlistDocument } from './document.ts';
import { DEFAULT_PLIST_PARSE_LIMITS } from './profile.ts';
import type { PlistParseLimits } from './profile.ts';
import {
  PLIST_EPOCH_OFFSET_UNIX,
  PlistArenaError,
  PlistDocument as PlistNativeDocument,
  PlistDocumentBuilder,
  PlistReal,
  plistBooleanValue,
  plistDataValue,
  plistDateValue,
  plistIntegerValue,
  plistRealValue,
  plistStringValue,
  plistUidValue,
} from './native.ts';
import type { PlistSyntaxKind } from './syntax.ts';

/** Style identifier `plist.xml-canonical` (RFC 0013 §10.1). */
const STYLE_XML = 'plist.xml-canonical';
/** Style identifier `plist.binary-canonical` (RFC 0013 §10.2). */
const STYLE_BINARY = 'plist.binary-canonical';
/** Versioned value-tree record name (RFC 0013 §9). */
const VALUE_TREE_RECORD = 'plist.value-tree@1';
/** The only admitted truncation policy (RFC 0013 §10.1). */
const TRUNCATE_POLICY = 'TruncateWithReport';
/** Fixed XML spelling of the plist epoch (RFC 0013 §9). */
const PLIST_EPOCH_SPELLING = '2001-01-01T00:00:00Z';
/** Stable truncation report/failure code (RFC 0013 §10.1, §12). */
const FRACTIONAL_DATE_CODE = 'plist.materialization.fractional-date@1';
/** Exact bits of `-0.0` (materialization.rs:152). */
const NEGATIVE_ZERO_BITS = 0x8000_0000_0000_0000n;
/** `2^53`: the largest magnitude at which every integral double is exactly representable. */
const EXACT_UNIX_SECONDS_BOUND = 9_007_199_254_740_992.0;

/** The two canonical materialization styles (materialization.rs:157-166). */
type Style = 'Xml' | 'Binary';

/** One validated `plist.value-tree@1` record. */
interface Record {
  readonly root: ValueNode;
  readonly policy: boolean;
}

/** One validated value record with its input path. */
interface ValueNode {
  readonly path: ValuePath;
  readonly kind: ValueKind;
}

/** One validated dictionary association. */
interface DictEntry {
  readonly key: string;
  readonly keyPath: ValuePath;
  readonly value: ValueNode;
}

/** Closed validated value kinds (materialization.rs:333-362). */
type ValueKind =
  | { readonly kind: 'Dict'; readonly entries: readonly DictEntry[] }
  | { readonly kind: 'Array'; readonly elements: readonly ValueNode[] }
  | { readonly kind: 'String'; readonly text: string }
  | { readonly kind: 'Integer'; readonly value: bigint }
  | { readonly kind: 'Real'; readonly real: PlistReal }
  | { readonly kind: 'Boolean'; readonly value: boolean }
  | { readonly kind: 'Date'; seconds: number }
  | { readonly kind: 'Data'; readonly bytes: Uint8Array }
  | { readonly kind: 'Uid'; readonly value: number };

/** One input value location paired with its exact target ordinal. */
interface InputItem {
  readonly path: ValuePath;
  readonly target: number;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

/** Materializes one `plist.value-tree@1` record into a new canonical plist document (RFC 0013 §10). */
export function materialize(
  value: PortableValue,
  request: MaterializationRequest,
): MaterializationResult<PlistDocument> {
  const analyzed: ValuePath[] = [];
  try {
    return { kind: 'Complete', value: materializeComplete(value, request, analyzed) };
  } catch (error) {
    if (!(error instanceof MaterializationFailure)) {
      throw error;
    }
    return {
      kind: 'Failed',
      value: new FailedMaterializationAttempt(
        error,
        new MaterializationReport([], request.limits()),
        analyzed,
      ),
    };
  }
}

/** Maps one plist-family materialization failure to its stable code (materialization.rs:78-94). */
export function plistMaterializationFailureCode(failure: MaterializationFailure): string {
  switch (failure.kind) {
    case 'Unrepresentable':
      return failure.valueKind === 'Date'
        ? FRACTIONAL_DATE_CODE
        : 'plist.materialization.unrepresentable@1';
    case 'ResourceLimit':
      return 'plist.materialization.resource-limit@1';
    default:
      return failure.code;
  }
}

function materializeComplete(
  value: PortableValue,
  request: MaterializationRequest,
  analyzed: ValuePath[],
): CompleteMaterialization<PlistDocument> {
  const style = validateRequest(request);
  const limits = request.limits();
  const record = validateRecord(value, request, analyzed);
  const { document: native, events, transformed } = buildNative(record, style, limits);
  const { bytes, items } = serialize(record, style, limits);
  const profile = style === 'Xml' ? ('XmlV1' as const) : ('BinaryV1' as const);
  let document: PlistDocument;
  try {
    document = parse(bytes, profile, { kind: 'ProfileDefault' }, parseLimitsFor(limits));
  } catch {
    throw new MaterializationFailure('FormationFailed');
  }
  if (document.formationStatus() !== 'Complete' || document.document() === null) {
    throw new MaterializationFailure('FormationFailed');
  }
  const nativeDocument = document.document();
  if (nativeDocument === null || !nativeDocument.equals(native)) {
    throw new MaterializationFailure('FormationFailed');
  }
  const report = new MaterializationReport(events, limits);
  const provenance = buildProvenance(items, document, style, limits);
  const fidelity: MaterializationFidelity = transformed ? 'Transformed' : 'Exact';
  return new CompleteMaterialization(document, fidelity, report, provenance);
}

/** Validates the request against the frozen style contracts (materialization.rs:236-266). */
function validateRequest(request: MaterializationRequest): Style {
  const profile = request.targetProfile();
  const style = request.style();
  let selected: Style;
  if (profile.id() === 'plist.xml' && profile.version() === 1 && style.id() === STYLE_XML && style.version() === 1) {
    selected = 'Xml';
  } else if (profile.id() === 'plist.binary' && profile.version() === 1 && style.id() === STYLE_BINARY && style.version() === 1) {
    selected = 'Binary';
  } else if ((profile.id() !== 'plist.xml' && profile.id() !== 'plist.binary') || profile.version() !== 1) {
    throw new MaterializationFailure('UnsupportedProfile');
  } else {
    throw new MaterializationFailure('UnsupportedStyle');
  }
  if (selected === 'Xml') {
    if (request.encoding().kind !== 'Utf8') {
      throw new MaterializationFailure('UnsupportedEncoding');
    }
    if (request.newline() !== 'Lf') {
      throw new MaterializationFailure('UnsupportedNewline');
    }
  } else {
    if (request.encoding().kind !== 'Binary') {
      throw new MaterializationFailure('UnsupportedEncoding');
    }
    if (request.newline() !== 'None') {
      throw new MaterializationFailure('UnsupportedNewline');
    }
  }
  return selected;
}

/** Parse limits for the closure reparse, derived from the request (materialization.rs:274-304). */
function parseLimitsFor(limits: MaterializationLimits): PlistParseLimits {
  return {
    ...DEFAULT_PLIST_PARSE_LIMITS,
    common: {
      maxSourceBytes: limits.maxOutputBytes,
      maxNestingDepth: limits.maxDepth + 2,
      maxTokenCount: limits.maxOutputBytes,
      maxNodeCount: limits.maxInputNodes,
      maxDiagnostics: limits.maxReportEntries,
    },
    maxDecodedUtf8Bytes: limits.maxOutputBytes * 3,
    maxDecodedScalars: limits.maxOutputBytes,
    maxObjectCount: limits.maxInputNodes * 2,
    maxContainerDepth: limits.maxDepth,
    maxDictEntries: limits.maxInputNodes,
    maxArrayElements: limits.maxInputNodes,
    maxDuplicateKeyGroupMembers: limits.maxInputNodes,
    maxStringCodeUnits: limits.maxOutputBytes,
    maxDataBytes: limits.maxOutputBytes,
    maxUidCount: limits.maxInputNodes,
    maxExtendedSizeIntegers: limits.maxInputNodes * 2,
    maxExtendedSizeValue: limits.maxInputNodes,
    maxOffsetIntSize: 8,
    maxObjectRefSize: 8,
    maxOffsetTableBytes: limits.maxOutputBytes * 8,
    maxSyntaxPieces: limits.maxOutputBytes,
    maxBinaryFacts: limits.maxOutputBytes * 16,
    maxConversionNodes: limits.maxInputNodes,
    maxReportEvents: limits.maxReportEntries,
    maxRecoveryRegions: limits.maxReportEntries,
  };
}

// ---------------------------------------------------------------------------
// Record validation (materialization.rs:306-655)
// ---------------------------------------------------------------------------

function validateRecord(value: PortableValue, request: MaterializationRequest, analyzed: ValuePath[]): Record {
  analyzed.push(ValuePath.root());
  const recordField = objectField(value, 'record');
  if (recordField === undefined || recordField.kind !== 'String' || recordField.value !== VALUE_TREE_RECORD) {
    throw new MaterializationFailure('InvalidRequest', { reason: 'input record is not plist.value-tree@1' });
  }
  let policy = false;
  const policyField = objectField(value, 'truncate_policy');
  if (policyField !== undefined) {
    if (policyField.kind !== 'String' || policyField.value !== TRUNCATE_POLICY) {
      throw new MaterializationFailure('InvalidRequest', { reason: 'unsupported truncate policy' });
    }
    policy = true;
  }
  const rootField = objectField(value, 'root');
  if (rootField === undefined) {
    throw new MaterializationFailure('InvalidRequest', { reason: 'missing record field: root' });
  }
  const rootPath = ValuePath.root().child({ kind: 'ObjectValue', name: 'root' });
  const validator = new Validator(request.limits());
  const root = validateValueNode(rootField, rootPath, validator, analyzed, 0);
  return { root, policy };
}

class Validator {
  readonly #limits: MaterializationLimits;
  nodes = 0;

  constructor(limits: MaterializationLimits) {
    this.#limits = limits;
  }

  step(): void {
    this.nodes += 1;
    if (this.nodes > this.#limits.maxInputNodes) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'input-nodes' });
    }
  }

  limits(): MaterializationLimits {
    return this.#limits;
  }
}

/** Validates one value of the record and its descendants (materialization.rs:438-655). */
function validateValueNode(
  value: PortableValue,
  path: ValuePath,
  validator: Validator,
  analyzed: ValuePath[],
  depth: number,
): ValueNode {
  validator.step();
  analyzed.push(path);
  const limits = validator.limits();
  let kind: ValueKind;
  if (value.kind === 'EntryMapping') {
    if (depth + 1 > limits.maxDepth) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'input-depth' });
    }
    const entries: DictEntry[] = [];
    for (let ordinal = 0; ordinal < value.entries.length; ordinal++) {
      const entry = value.entries[ordinal];
      if (entry.key.kind !== 'String') {
        throw new MaterializationFailure('Unrepresentable', {
          path: path.child({ kind: 'EntryKey', index: BigInt(ordinal) }),
          valueKind: entry.key.kind,
        });
      }
      const child = validateValueNode(
        entry.value,
        path.child({ kind: 'EntryValue', index: BigInt(ordinal) }),
        validator,
        analyzed,
        depth + 1,
      );
      entries.push({ key: entry.key.value, keyPath: path.child({ kind: 'EntryKey', index: BigInt(ordinal) }), value: child });
    }
    kind = { kind: 'Dict', entries };
  } else if (value.kind === 'Sequence') {
    if (depth + 1 > limits.maxDepth) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'input-depth' });
    }
    const elements: ValueNode[] = [];
    for (let index = 0; index < value.items.length; index++) {
      elements.push(
        validateValueNode(
          value.items[index],
          path.child({ kind: 'SequenceElement', index: BigInt(index) }),
          validator,
          analyzed,
          depth + 1,
        ),
      );
    }
    kind = { kind: 'Array', elements };
  } else if (value.kind === 'String') {
    if (value.value.length > limits.maxOutputBytes) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'output-bytes' });
    }
    kind = { kind: 'String', text: value.value };
  } else if (value.kind === 'Integer') {
    if (value.value > 0x7fffffffffffffffn || value.value < -0x8000000000000000n) {
      throw new MaterializationFailure('Unrepresentable', { path, valueKind: 'Integer' });
    }
    kind = { kind: 'Integer', value: value.value };
  } else if (value.kind === 'BinaryFloat32') {
    kind = { kind: 'Real', real: PlistReal.fromBits('Float32', BigInt(value.bits)) };
  } else if (value.kind === 'BinaryFloat64') {
    kind = { kind: 'Real', real: PlistReal.fromBits('Float64', value.bits) };
  } else if (value.kind === 'Decimal') {
    const converted = decimalToF64(value.coefficient, value.exponent);
    if (converted === null) {
      throw new MaterializationFailure('Unrepresentable', { path, valueKind: 'Decimal' });
    }
    kind = { kind: 'Real', real: PlistReal.double(converted) };
  } else if (value.kind === 'Boolean') {
    kind = { kind: 'Boolean', value: value.value };
  } else if (value.kind === 'Bytes') {
    if (value.value.length > limits.maxOutputBytes) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'output-bytes' });
    }
    kind = { kind: 'Data', bytes: value.value };
  } else if (value.kind === 'Object') {
    if (objectField(value, 'kind') !== undefined) {
      // The explicit `{kind, ...}` record spelling is not the
      // `plist.value-tree@1` record (RFC 0013 §9).
      throw new MaterializationFailure('Unrepresentable', { path, valueKind: 'Object' });
    }
    const epoch = objectField(value, 'epoch');
    const seconds = objectField(value, 'seconds');
    if (epoch !== undefined && seconds !== undefined) {
      if (epoch.kind !== 'String' || epoch.value !== PLIST_EPOCH_SPELLING) {
        throw new MaterializationFailure('InvalidRequest', {
          reason: 'date epoch is not 2001-01-01T00:00:00Z',
        });
      }
      let secondsValue: number;
      if (seconds.kind === 'BinaryFloat64') {
        secondsValue = float64FromBits(seconds.bits);
      } else if (seconds.kind === 'Decimal') {
        const converted = decimalToF64(seconds.coefficient, seconds.exponent);
        if (converted === null) {
          throw new MaterializationFailure('Unrepresentable', { path, valueKind: 'Date' });
        }
        secondsValue = converted;
      } else {
        throw new MaterializationFailure('Unrepresentable', { path, valueKind: 'Date' });
      }
      if (!Number.isFinite(secondsValue)) {
        throw new MaterializationFailure('Unrepresentable', { path, valueKind: 'Date' });
      }
      kind = { kind: 'Date', seconds: secondsValue };
    } else if (objectField(value, 'uid') !== undefined) {
      const uid = objectField(value, 'uid')!;
      if (uid.kind !== 'Integer' || uid.value < 0n || uid.value > 0xffffffffn) {
        throw new MaterializationFailure('Unrepresentable', {
          path: path.child({ kind: 'ObjectValue', name: 'uid' }),
          valueKind: uid.kind,
        });
      }
      kind = { kind: 'Uid', value: Number(uid.value) };
    } else if (objectField(value, 'hex') !== undefined) {
      const hex = objectField(value, 'hex')!;
      if (hex.kind !== 'String') {
        throw new MaterializationFailure('Unrepresentable', {
          path: path.child({ kind: 'ObjectValue', name: 'hex' }),
          valueKind: hex.kind,
        });
      }
      if (hex.value.length / 2 > limits.maxOutputBytes) {
        throw new MaterializationFailure('ResourceLimit', { reason: 'output-bytes' });
      }
      const bytes = decodeHex(hex.value);
      if (bytes === null) {
        throw new MaterializationFailure('Unrepresentable', {
          path: path.child({ kind: 'ObjectValue', name: 'hex' }),
          valueKind: 'String',
        });
      }
      kind = { kind: 'Data', bytes };
    } else {
      // A dictionary spelled as an ordered JSON object.
      if (depth + 1 > limits.maxDepth) {
        throw new MaterializationFailure('ResourceLimit', { reason: 'input-depth' });
      }
      const entries: DictEntry[] = [];
      for (let ordinal = 0; ordinal < value.entries.length; ordinal++) {
        const entry = value.entries[ordinal];
        const child = validateValueNode(
          entry.value,
          path.child({ kind: 'EntryValue', index: BigInt(ordinal) }),
          validator,
          analyzed,
          depth + 1,
        );
        entries.push({ key: entry.key, keyPath: path.child({ kind: 'EntryKey', index: BigInt(ordinal) }), value: child });
      }
      kind = { kind: 'Dict', entries };
    }
  } else {
    throw new MaterializationFailure('Unrepresentable', { path, valueKind: value.kind });
  }
  return { path, kind };
}

function objectField(value: PortableValue, name: string): PortableValue | undefined {
  if (value.kind !== 'Object') {
    return undefined;
  }
  return value.entries.find((entry) => entry.key === name)?.value;
}

/** Converts one exact decimal to its double value (materialization.rs:665-679). */
function decimalToF64(coefficient: bigint, exponent: bigint): number | null {
  if (coefficient > BigInt(Number.MAX_SAFE_INTEGER) || coefficient < -BigInt(Number.MAX_SAFE_INTEGER)) {
    return null;
  }
  if (exponent > 308n || exponent < -308n) {
    return null;
  }
  let value = Number(coefficient);
  if (exponent > 0n) {
    value *= 10 ** Number(exponent);
  } else if (exponent < 0n) {
    value /= 10 ** Number(-exponent);
  }
  return value;
}

/** Strictly decodes one even-length hex string (materialization.rs:682-700). */
function decodeHex(text: string): Uint8Array | null {
  if (text.length % 2 !== 0 || !/^[0-9a-fA-F]*$/.test(text)) {
    return null;
  }
  const bytes = new Uint8Array(text.length / 2);
  for (let index = 0; index < bytes.length; index++) {
    bytes[index] = (hexDigit(text.charCodeAt(index * 2)) << 4) | hexDigit(text.charCodeAt(index * 2 + 1));
  }
  return bytes;
}

function hexDigit(code: number): number {
  if (code >= 0x30 && code <= 0x39) return code - 0x30;
  if (code >= 0x61 && code <= 0x66) return code - 0x61 + 10;
  return code - 0x41 + 10;
}

// ---------------------------------------------------------------------------
// Native document building (materialization.rs:712-868)
// ---------------------------------------------------------------------------

/** Builds the promised native document, applying the XML expressibility boundary. */
function buildNative(
  record: Record,
  style: Style,
  limits: MaterializationLimits,
): { readonly document: PlistNativeDocument; readonly events: Diagnostic[]; readonly transformed: boolean } {
  const builder = new PlistDocumentBuilder({
    maxObjects: limits.maxInputNodes,
    maxContainerDepth: limits.maxDepth,
  });
  const events: Diagnostic[] = [];
  const transformed = { value: false };
  const root = buildValue(builder, record.root, style, record.policy, { events, transformed }, limits);
  try {
    const document = builder.build(root);
    return { document, events, transformed: transformed.value };
  } catch (error) {
    if (error instanceof PlistArenaError) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'input-nodes' });
    }
    throw error;
  }
}

function buildValue(
  builder: PlistDocumentBuilder,
  node: ValueNode,
  style: Style,
  policy: boolean,
  state: { readonly events: Diagnostic[]; readonly transformed: { value: boolean } },
  limits: MaterializationLimits,
): number {
  switch (node.kind.kind) {
    case 'Dict': {
      const entries: Array<{ readonly key: string; readonly value: number }> = [];
      for (const entry of node.kind.entries) {
        if (style === 'Xml' && !isXmlText(entry.key)) {
          throw new MaterializationFailure('Unrepresentable', {
            path: entry.keyPath,
            valueKind: 'String',
          });
        }
        const value = buildValue(builder, entry.value, style, policy, state, limits);
        entries.push({ key: entry.key, value });
      }
      return builder.add({ kind: 'Dict', entries: Object.freeze(entries) });
    }
    case 'Array': {
      const elements: number[] = [];
      for (const element of node.kind.elements) {
        elements.push(buildValue(builder, element, style, policy, state, limits));
      }
      return builder.add({ kind: 'Array', elements: Object.freeze(elements) });
    }
    case 'String': {
      if (style === 'Xml' && (classifySurrogates(node.kind.text) === 'UnpairedSurrogate' || !isXmlText(node.kind.text))) {
        throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'String' });
      }
      return builder.add(plistStringValue(node.kind.text));
    }
    case 'Integer':
      return builder.add(plistIntegerValue(node.kind.value));
    case 'Real': {
      if (style === 'Xml') {
        if (node.kind.real.width() === 'Float32') {
          throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'BinaryFloat32' });
        }
        if (!realExpressible(node.kind.real)) {
          throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'BinaryFloat64' });
        }
      }
      return builder.add(plistRealValue(node.kind.real));
    }
    case 'Boolean':
      return builder.add(plistBooleanValue(node.kind.value));
    case 'Date': {
      if (style === 'Xml') {
        const nodeCopy = node.kind;
        if (bitsOfFloat64(nodeCopy.seconds) === NEGATIVE_ZERO_BITS) {
          throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'Date' });
        }
        try {
          wholeSecondDate(nodeCopy.seconds);
        } catch (error) {
          if (error instanceof DateRangeError && error.kind === 'FractionalSeconds') {
            if (!policy) {
              throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'Date' });
            }
            const original = nodeCopy.seconds;
            const truncated = Math.trunc(original);
            if (bitsOfFloat64(truncated) === NEGATIVE_ZERO_BITS || wholeSecondDateSafe(truncated) === null) {
              throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'Date' });
            }
            nodeCopy.seconds = truncated;
            state.events.push(
              diagnostic(FRACTIONAL_DATE_CODE, 'Materialization', 'Warning', null, BigInt(state.events.length), {
                arguments: [
                  ['path', renderPath(node.path)],
                  ['seconds', String(original)],
                ],
              }),
            );
            state.transformed.value = true;
          } else {
            throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'Date' });
          }
        }
      }
      return builder.add(plistDateValue(node.kind.seconds));
    }
    case 'Data':
      return builder.add(plistDataValue(node.kind.bytes));
    case 'Uid': {
      if (style === 'Xml') {
        throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'Integer' });
      }
      return builder.add(plistUidValue(node.kind.value));
    }
  }
}

/** Stable path rendering for diagnostic arguments (materialization.rs:891-917). */
function renderPath(path: ValuePath): string {
  let out = '';
  for (const segment of path.segments()) {
    switch (segment.kind) {
      case 'ObjectValue':
        out += `/${segment.name}`;
        break;
      case 'SequenceElement':
        out += `[${segment.index}]`;
        break;
      case 'EntryKey':
        out += `[key ${segment.index}]`;
        break;
      case 'EntryValue':
        out += `[value ${segment.index}]`;
        break;
    }
  }
  return out;
}

/** Whether the exact bits of one real survive the XML spelling (materialization.rs:1253-1265). */
function realExpressible(real: PlistReal): boolean {
  const value = real.asF64();
  if (Number.isNaN(value)) {
    return bitsOfFloat64(value) === bitsOfFloat64(Number.NaN);
  }
  if (!Number.isFinite(value)) {
    return true;
  }
  return bitsOfFloat64(Number(value.toString())) === bitsOfFloat64(value);
}

/** XML 1.0 `Char` production (materialization.rs:1372-1379). */
function isXmlCharCode(code: number): boolean {
  return (
    code === 0x09 ||
    code === 0x0a ||
    code === 0x0d ||
    (code >= 0x20 && code <= 0xd7ff) ||
    (code >= 0xe000 && code <= 0xfffd) ||
    (code >= 0x10000 && code <= 0x10ffff)
  );
}

/** Whether every scalar of one UTF-16 sequence is an XML 1.0 character (materialization.rs:1383-1407). */
function isXmlText(text: string): boolean {
  return classifySurrogates(text) === 'WellFormedUnicode' && [...text].every((c) => isXmlCharCode(c.codePointAt(0)!));
}

function classifySurrogates(text: string): 'WellFormedUnicode' | 'UnpairedSurrogate' {
  for (let index = 0; index < text.length; index++) {
    const unit = text.charCodeAt(index);
    if (unit >= 0xd800 && unit <= 0xdbff) {
      const low = index + 1 < text.length ? text.charCodeAt(index + 1) : 0;
      if (low >= 0xdc00 && low <= 0xdfff) {
        index += 1;
      } else {
        return 'UnpairedSurrogate';
      }
    } else if (unit >= 0xdc00 && unit <= 0xdfff) {
      return 'UnpairedSurrogate';
    }
  }
  return 'WellFormedUnicode';
}

class DateRangeError extends Error {
  readonly kind: 'FractionalSeconds' | 'YearOutOfRange';
  constructor(kind: 'FractionalSeconds' | 'YearOutOfRange') {
    super(`date range: ${kind}`);
    this.kind = kind;
  }
}

/** Decomposes exact plist-epoch seconds into XML calendar fields (materialization.rs:1292-1313). */
function wholeSecondDate(seconds: number): { year: number; month: number; day: number; hour: number; minute: number; second: number } {
  if (seconds % 1 !== 0) {
    throw new DateRangeError('FractionalSeconds');
  }
  const result = wholeSecondDateSafe(seconds);
  if (result === null) {
    throw new DateRangeError('YearOutOfRange');
  }
  return result;
}

function wholeSecondDateSafe(
  seconds: number,
): { year: number; month: number; day: number; hour: number; minute: number; second: number } | null {
  const unix = seconds + PLIST_EPOCH_OFFSET_UNIX;
  if (Math.abs(unix) >= EXACT_UNIX_SECONDS_BOUND) {
    return null;
  }
  const unixInt = Math.trunc(unix);
  const days = Math.floor(unixInt / 86400);
  const secondsOfDay = unixInt % 86400;
  const civil = civilFromDays(days);
  if (Math.abs(civil.year) > 0xffffffff) {
    return null;
  }
  return {
    year: civil.year,
    month: civil.month,
    day: civil.day,
    hour: Math.floor(secondsOfDay / 3600),
    minute: Math.floor((secondsOfDay % 3600) / 60),
    second: secondsOfDay % 60,
  };
}

/** Proleptic Gregorian calendar date of `days` since the Unix epoch (materialization.rs:1317-1330). */
function civilFromDays(days: number): { year: number; month: number; day: number } {
  const z = days + 719468;
  const era = z >= 0 ? z : z - 146096;
  const eraFloor = Math.floor(era / 146097);
  const dayOfEra = z - eraFloor * 146097;
  const yearOfEra = Math.floor((dayOfEra - Math.floor(dayOfEra / 1460) + Math.floor(dayOfEra / 36524) - Math.floor(dayOfEra / 146096)) / 365);
  let year = yearOfEra + eraFloor * 400;
  const dayOfYear = dayOfEra - (365 * yearOfEra + Math.floor(yearOfEra / 4) - Math.floor(yearOfEra / 100));
  const monthPrime = Math.floor((5 * dayOfYear + 2) / 153);
  const day = dayOfYear - Math.floor((153 * monthPrime + 2) / 5) + 1;
  const month = monthPrime + (monthPrime < 10 ? 3 : -9);
  year = month <= 2 ? year + 1 : year;
  return { year, month, day };
}

// ---------------------------------------------------------------------------
// Serialization
// ---------------------------------------------------------------------------

/** Serializes one record under the requested style (materialization.rs:1098-1118, 1414-1452). */
function serialize(record: Record, style: Style, limits: MaterializationLimits): { readonly bytes: Uint8Array; readonly items: InputItem[] } {
  if (style === 'Xml') {
    return serializeXml(record, limits);
  }
  return serializeBinary(record, limits);
}

// -- XML ---------------------------------------------------------------------

function serializeXml(record: Record, limits: MaterializationLimits): { readonly bytes: Uint8Array; readonly items: InputItem[] } {
  const out = { text: '<?xml version="1.0" encoding="UTF-8"?>\n' };
  out.text += '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n';
  out.text += '<plist version="1.0">\n';
  const items: InputItem[] = [];
  const rank = { value: 0 };
  emitValue(out, record.root, 1, items, rank, limits);
  out.text += '</plist>\n';
  return { bytes: new TextEncoder().encode(out.text), items };
}

/** Emits one value element at the given depth (materialization.rs:1123-1209). */
function emitValue(
  out: { text: string },
  node: ValueNode,
  depth: number,
  items: InputItem[],
  rank: { value: number },
  limits: MaterializationLimits,
): void {
  switch (node.kind.kind) {
    case 'Dict': {
      out.text += writeIndent(depth);
      if (node.kind.entries.length === 0) {
        out.text += '<dict></dict>\n';
      } else {
        out.text += '<dict>\n';
        for (const entry of node.kind.entries) {
          out.text += writeIndent(depth + 1);
          out.text += '<key>';
          out.text += escapeXmlText(entry.key);
          out.text += '</key>\n';
          emitValue(out, entry.value, depth + 1, items, rank, limits);
        }
        out.text += writeIndent(depth);
        out.text += '</dict>\n';
      }
      break;
    }
    case 'Array': {
      out.text += writeIndent(depth);
      if (node.kind.elements.length === 0) {
        out.text += '<array></array>\n';
      } else {
        out.text += '<array>\n';
        for (const element of node.kind.elements) {
          emitValue(out, element, depth + 1, items, rank, limits);
        }
        out.text += writeIndent(depth);
        out.text += '</array>\n';
      }
      break;
    }
    case 'String':
      out.text += writeIndent(depth);
      out.text += '<string>';
      out.text += escapeXmlText(node.kind.text);
      out.text += '</string>\n';
      break;
    case 'Integer':
      out.text += writeIndent(depth);
      out.text += `<integer>${node.kind.value}</integer>\n`;
      break;
    case 'Real':
      out.text += writeIndent(depth);
      out.text += `<real>${renderReal(node.kind.real)}</real>\n`;
      break;
    case 'Boolean':
      out.text += writeIndent(depth);
      out.text += node.kind.value ? '<true/>\n' : '<false/>\n';
      break;
    case 'Date': {
      out.text += writeIndent(depth);
      const fields = wholeSecondDate(node.kind.seconds);
      out.text += `<date>${renderDate(fields)}</date>\n`;
      break;
    }
    case 'Data':
      out.text += writeIndent(depth);
      out.text += '<data>';
      out.text += encodeBase64Wrapped(node.kind.bytes, depth);
      out.text += '</data>\n';
      break;
    case 'Uid':
      throw new MaterializationFailure('Unrepresentable', { path: node.path, valueKind: 'Integer' });
  }
  items.push({ path: node.path, target: rank.value });
  rank.value += 1;
  if (out.text.length > limits.maxOutputBytes) {
    throw new MaterializationFailure('ResourceLimit', { reason: 'output-bytes' });
  }
}

function writeIndent(depth: number): string {
  return '    '.repeat(depth);
}

/** Escapes XML text content (RFC 0013 §4.9, §10.1; materialization.rs:1221-1231). */
function escapeXmlText(text: string): string {
  let out = '';
  for (const character of text) {
    switch (character) {
      case '&':
        out += '&amp;';
        break;
      case '<':
        out += '&lt;';
        break;
      case '>':
        out += '&gt;';
        break;
      case '\r':
        out += '&#13;';
        break;
      default:
        out += character;
        break;
    }
  }
  return out;
}

/** Deterministic shortest-round-trip decimal spelling of one real (materialization.rs:1235-1248). */
function renderReal(real: PlistReal): string {
  const value = real.asF64();
  if (Number.isNaN(value)) {
    return 'nan';
  }
  if (!Number.isFinite(value)) {
    return Object.is(value, -Infinity) ? '-inf' : 'inf';
  }
  return String(value);
}

/** Whole-second XML date spelling (materialization.rs:1269-1275). */
function renderDate(fields: { year: number; month: number; day: number; hour: number; minute: number; second: number }): string {
  const sign = fields.year < 0 ? '-' : '';
  const year = Math.abs(fields.year).toString().padStart(4, '0');
  const pad = (value: number) => String(value).padStart(2, '0');
  return `${sign}${year}-${pad(fields.month)}-${pad(fields.day)}T${pad(fields.hour)}:${pad(fields.minute)}:${pad(fields.second)}Z`;
}

/** Canonical standard-alphabet base64 wrapped at `76 - 8 * depth` per line (materialization.rs:1338-1369). */
function encodeBase64Wrapped(bytes: Uint8Array, depth: number): string {
  const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
  const budget = Math.max(76 - 8 * depth, 1);
  let out = '';
  let line = 0;
  for (let at = 0; at < bytes.length; at += 3) {
    const first = bytes[at];
    const second = at + 1 < bytes.length ? bytes[at + 1] : 0;
    const third = at + 2 < bytes.length ? bytes[at + 2] : 0;
    if (line + 4 > budget && line > 0) {
      out += '\n';
      out += writeIndent(depth);
      line = 0;
    }
    out += ALPHABET[first >> 2];
    out += ALPHABET[((first & 0x03) << 4) | (second >> 4)];
    out += at + 1 < bytes.length ? ALPHABET[((second & 0x0f) << 2) | (third >> 6)] : '=';
    out += at + 2 < bytes.length ? ALPHABET[third & 0x3f] : '=';
    line += 4;
  }
  return out;
}

// -- Binary -------------------------------------------------------------------

/** Content key of one scalar object (materialization.rs:946-992). */
type ScalarKey =
  | { readonly kind: 'String'; readonly text: string }
  | { readonly kind: 'Integer'; readonly value: bigint }
  | { readonly kind: 'Real'; readonly bits: bigint; readonly width: 'Float64' | 'Float32' }
  | { readonly kind: 'Boolean'; readonly value: boolean }
  | { readonly kind: 'Date'; readonly bits: bigint }
  | { readonly kind: 'Data'; readonly bytes: Uint8Array }
  | { readonly kind: 'Uid'; readonly value: number };

function scalarKeyOf(node: ValueNode): ScalarKey {
  switch (node.kind.kind) {
    case 'String':
      return { kind: 'String', text: node.kind.text };
    case 'Integer':
      return { kind: 'Integer', value: node.kind.value };
    case 'Real':
      return { kind: 'Real', bits: node.kind.real.bits(), width: node.kind.real.width() };
    case 'Boolean':
      return { kind: 'Boolean', value: node.kind.value };
    case 'Date':
      return { kind: 'Date', bits: bitsOfFloat64(node.kind.seconds) };
    case 'Data':
      return { kind: 'Data', bytes: node.kind.bytes };
    case 'Uid':
      return { kind: 'Uid', value: node.kind.value };
    case 'Dict':
    case 'Array':
      throw new Error('internal: containers are planned before their children');
  }
}

/** Whether this scalar participates in first-occurrence deduplication (materialization.rs:984-992). */
function deduplicates(key: ScalarKey): boolean {
  return key.kind === 'String' || key.kind === 'Integer' || key.kind === 'Real' || key.kind === 'Date' || key.kind === 'Data';
}

type PlannedObject =
  | { readonly kind: 'Dict'; keys: number[]; values: number[] }
  | { readonly kind: 'Array'; elements: number[] }
  | { readonly kind: 'Scalar'; readonly key: ScalarKey };

/** Plans the document-ordered binary object table (materialization.rs:1011-1096). */
function planBinary(root: ValueNode): { readonly objects: PlannedObject[]; readonly items: InputItem[] } {
  const objects: PlannedObject[] = [];
  const items: InputItem[] = [];
  const cache = new Map<string, number>();
  const scalarKeyId = (key: ScalarKey): string => {
    switch (key.kind) {
      case 'String':
        return `s:${key.text}`;
      case 'Integer':
        return `i:${key.value}`;
      case 'Real':
        return `r:${key.width}:${key.bits}`;
      case 'Boolean':
        return `b:${key.value}`;
      case 'Date':
        return `d:${key.bits}`;
      case 'Data':
        return `x:${hexOf(key.bytes)}`;
      case 'Uid':
        return `u:${key.value}`;
    }
  };
  const planNode = (node: ValueNode): number => {
    switch (node.kind.kind) {
      case 'Dict': {
        const index = objects.length;
        objects.push({ kind: 'Dict', keys: [], values: [] });
        items.push({ path: node.path, target: index });
        const keyRefs: number[] = [];
        for (const entry of node.kind.entries) {
          const key = scalarKeyOf({ path: entry.keyPath, kind: { kind: 'String', text: entry.key } });
          const id = scalarKeyId(key);
          let keyIndex = cache.get(id);
          if (keyIndex === undefined) {
            keyIndex = objects.length;
            objects.push({ kind: 'Scalar', key });
            cache.set(id, keyIndex);
          }
          keyRefs.push(keyIndex);
        }
        const valueRefs = node.kind.entries.map((entry) => planNode(entry.value));
        (objects[index] as { kind: 'Dict'; keys: number[]; values: number[] }).keys = keyRefs;
        (objects[index] as { kind: 'Dict'; keys: number[]; values: number[] }).values = valueRefs;
        return index;
      }
      case 'Array': {
        const index = objects.length;
        objects.push({ kind: 'Array', elements: [] });
        items.push({ path: node.path, target: index });
        const elements = node.kind.elements.map((element) => planNode(element));
        (objects[index] as { kind: 'Array'; elements: number[] }).elements = elements;
        return index;
      }
      default: {
        const key = scalarKeyOf(node);
        if (deduplicates(key)) {
          const id = scalarKeyId(key);
          const cached = cache.get(id);
          if (cached !== undefined) {
            items.push({ path: node.path, target: cached });
            return cached;
          }
          const index = objects.length;
          objects.push({ kind: 'Scalar', key });
          cache.set(id, index);
          items.push({ path: node.path, target: index });
          return index;
        }
        const index = objects.length;
        objects.push({ kind: 'Scalar', key });
        items.push({ path: node.path, target: index });
        return index;
      }
    }
  };
  planNode(root);
  return { objects, items };
}

function serializeBinary(record: Record, limits: MaterializationLimits): { readonly bytes: Uint8Array; readonly items: InputItem[] } {
  const plan = planBinary(record.root);
  const numObjects = plan.objects.length;
  const refSize = refSizeFor(numObjects);
  const chunks: Uint8Array[] = [new TextEncoder().encode('bplist00')];
  const offsets: number[] = [];
  let total = 8;
  for (const object of plan.objects) {
    offsets.push(total);
    const bytes = writePlannedObject(object, refSize);
    total += bytes.length;
    if (total > limits.maxOutputBytes) {
      throw new MaterializationFailure('ResourceLimit', { reason: 'output-bytes' });
    }
    chunks.push(bytes);
  }
  const offsetTableOffset = total;
  const offsetIntSize = refSizeFor(offsetTableOffset);
  const table = new Uint8Array(numObjects * offsetIntSize);
  for (let index = 0; index < numObjects; index++) {
    writeBe(table, index * offsetIntSize, BigInt(offsets[index]), offsetIntSize);
  }
  chunks.push(table);
  const trailer = new Uint8Array(32);
  trailer[5] = 0; // sortVersion
  trailer[6] = offsetIntSize;
  trailer[7] = refSize;
  writeBe(trailer, 8, BigInt(numObjects), 8); // numObjects
  writeBe(trailer, 16, 0n, 8); // topObject: the root value is always object 0
  writeBe(trailer, 24, BigInt(offsetTableOffset), 8); // offsetTableOffset
  chunks.push(trailer);
  const totalLength = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
  const bytes = new Uint8Array(totalLength);
  let at = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, at);
    at += chunk.length;
  }
  return { bytes, items: plan.items };
}

/** Writes one planned object: marker, size, payload, and references (materialization.rs:1456-1520). */
function writePlannedObject(object: PlannedObject, refSize: number): Uint8Array {
  switch (object.kind) {
    case 'Dict': {
      const count = object.keys.length;
      const parts: Uint8Array[] = [sizedMarker(0xd0, count)];
      for (const key of object.keys) {
        parts.push(beBytes(BigInt(key), refSize));
      }
      for (const value of object.values) {
        parts.push(beBytes(BigInt(value), refSize));
      }
      return concat(parts);
    }
    case 'Array': {
      const parts: Uint8Array[] = [sizedMarker(0xa0, object.elements.length)];
      for (const element of object.elements) {
        parts.push(beBytes(BigInt(element), refSize));
      }
      return concat(parts);
    }
    case 'Scalar':
      return writeScalarObject(object.key);
  }
}

function writeScalarObject(key: ScalarKey): Uint8Array {
  switch (key.kind) {
    case 'String': {
      const units = key.text;
      const ascii = [...units].every((c) => c.charCodeAt(0) < 0x80);
      const parts: Uint8Array[] = [sizedMarker(ascii ? 0x50 : 0x60, units.length)];
      if (ascii) {
        parts.push(new TextEncoder().encode(units));
      } else {
        const bytes = new Uint8Array(units.length * 2);
        for (let index = 0; index < units.length; index++) {
          bytes[index * 2] = units.charCodeAt(index) >> 8;
          bytes[index * 2 + 1] = units.charCodeAt(index) & 0xff;
        }
        parts.push(bytes);
      }
      return concat(parts);
    }
    case 'Integer': {
      const width = integerWidth(key.value);
      const parts: Uint8Array[] = [new Uint8Array([0x10 | widthTrailingZeros(width)])];
      parts.push(beBytes(key.value & 0xffffffffffffffffn, width));
      return concat(parts);
    }
    case 'Real': {
      if (key.width === 'Float64') {
        const parts: Uint8Array[] = [new Uint8Array([0x23])];
        parts.push(beBytes(key.bits, 8));
        return concat(parts);
      }
      const parts: Uint8Array[] = [new Uint8Array([0x22])];
      parts.push(beBytes(key.bits, 4));
      return concat(parts);
    }
    case 'Boolean':
      return new Uint8Array([key.value ? 0x09 : 0x08]);
    case 'Date': {
      const parts: Uint8Array[] = [new Uint8Array([0x33])];
      parts.push(beBytes(key.bits, 8));
      return concat(parts);
    }
    case 'Data': {
      const parts: Uint8Array[] = [sizedMarker(0x40, key.bytes.length)];
      parts.push(key.bytes);
      return concat(parts);
    }
    case 'Uid': {
      const width = uidWidth(key.value);
      const parts: Uint8Array[] = [new Uint8Array([0x80 | (width - 1)])];
      parts.push(beBytes(BigInt(key.value), width));
      return concat(parts);
    }
  }
}

/** One sized marker; counts of 15 or more use the extended-size sentinel (materialization.rs:1549-1559). */
function sizedMarker(marker: number, count: number): Uint8Array {
  if (count < 0x0f) {
    return new Uint8Array([marker | count]);
  }
  const width = unsignedWidth(BigInt(count));
  const parts: Uint8Array[] = [new Uint8Array([marker | 0x0f, 0x10 | widthTrailingZeros(width)])];
  parts.push(beBytes(BigInt(count), width));
  return concat(parts);
}

/** Smallest width whose capacity exceeds `max_index` (materialization.rs:1574-1582). */
function refSizeFor(maxIndex: number): number {
  let size = 1;
  let capacity = 256;
  while (maxIndex >= capacity && size < 8) {
    size += 1;
    capacity *= 256;
  }
  return size;
}

/** Minimal marker width for one signed 64-bit integer (materialization.rs:1586-1591). */
function integerWidth(value: bigint): number {
  if (value >= 0n) {
    return unsignedWidth(value);
  }
  return 8;
}

function unsignedWidth(value: bigint): number {
  if (value <= 0xffn) return 1;
  if (value <= 0xffffn) return 2;
  if (value <= 0xffffffffn) return 4;
  return 8;
}

/** Minimal byte width of one unsigned 32-bit UID value (materialization.rs:1607-1617). */
function uidWidth(value: number): number {
  if (value <= 0xff) return 1;
  if (value <= 0xffff) return 2;
  if (value <= 0xffffff) return 3;
  return 4;
}

function widthTrailingZeros(width: number): number {
  switch (width) {
    case 1:
      return 0;
    case 2:
      return 1;
    case 4:
      return 2;
    default:
      return 3;
  }
}

/** Appends one big-endian unsigned value of exactly `width` bytes at `offset`. */
function writeBe(bytes: Uint8Array, offset: number, value: bigint, width: number): void {
  for (let shift = 0; shift < width; shift++) {
    bytes[offset + width - 1 - shift] = Number((value >> BigInt(8 * shift)) & 0xffn);
  }
}

/** One big-endian unsigned value of exactly `width` bytes. */
function beBytes(value: bigint, width: number): Uint8Array {
  const bytes = new Uint8Array(width);
  writeBe(bytes, 0, value, width);
  return bytes;
}

function concat(parts: readonly Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const bytes = new Uint8Array(total);
  let at = 0;
  for (const part of parts) {
    bytes.set(part, at);
    at += part.length;
  }
  return bytes;
}

// ---------------------------------------------------------------------------
// Provenance (materialization.rs:1619-1764)
// ---------------------------------------------------------------------------

function buildProvenance(
  items: InputItem[],
  document: PlistDocument,
  style: Style,
  limits: MaterializationLimits,
): MaterializationProvenanceMap {
  const authority = document.authorityInternal();
  const identity = document.snapshotIdentity();
  const origins: MaterializedOrigin[] = [];
  if (style === 'Binary') {
    const facts = document.binaryFacts();
    if (facts === null) {
      throw new MaterializationFailure('FormationFailed');
    }
    for (const item of items) {
      const fact = facts.objects()[item.target];
      if (fact === undefined) {
        throw new MaterializationFailure('FormationFailed');
      }
      origins.push(
        new MaterializedOrigin(
          identity,
          authority.nodeRef(BigInt(fact.index()), 'PlistValue'),
          fact.span(),
          'Direct',
        ),
      );
    }
  } else {
    const spans = xmlValueSpans(document);
    for (const item of items) {
      const span = spans[item.target];
      if (span === undefined) {
        throw new MaterializationFailure('FormationFailed');
      }
      origins.push(
        new MaterializedOrigin(
          identity,
          authority.nodeRef(BigInt(item.target), 'PlistValue'),
          span,
          'Direct',
        ),
      );
    }
  }
  const entries = items.map(
    (item, index) =>
      new MaterializationProvenanceEntry(
        { kind: 'Value', path: item.path },
        [origins[index]],
      ),
  );
  return MaterializationProvenanceMap.create(entries, identity, limits);
}

/** Reconstructs the value element spans of one reparsed XML document, in arena (close-tag) order. */
function xmlValueSpans(document: PlistDocument): Span[] {
  const pieces = document.losslessStructuralIndex()?.pieces();
  const kinds = document.losslessSyntaxKinds();
  if (pieces === undefined || kinds === null) {
    throw new MaterializationFailure('FormationFailed');
  }
  const source = document.source().bytes();
  const authority = document.authorityInternal();
  const spans: Span[] = [];
  const stack: Array<{ readonly start: number; readonly kind: PlistSyntaxKind }> = [];
  const openKinds = new Set<PlistSyntaxKind>([
    'dict-open',
    'array-open',
    'string-open',
    'integer-open',
    'real-open',
    'date-open',
    'data-open',
  ]);
  const closeKinds = new Set<PlistSyntaxKind>([
    'dict-close',
    'array-close',
    'string-close',
    'integer-close',
    'real-close',
    'date-close',
    'data-close',
  ]);
  for (let index = 0; index < pieces.length; index++) {
    const span = pieces[index].span();
    const kind = kinds[index];
    if (openKinds.has(kind)) {
      const raw = source.slice(span.startByte(), span.endByte());
      if (raw.length !== 1 || raw[0] !== 0x3e /* > */) {
        stack.push({ start: span.startByte(), kind });
      }
    } else if (closeKinds.has(kind)) {
      const open = stack.pop();
      if (open === undefined) {
        throw new MaterializationFailure('FormationFailed');
      }
      spans.push(authority.span(open.start, span.endByte()));
    } else if (kind === 'true' || kind === 'false') {
      const raw = source.slice(span.startByte(), span.endByte());
      const rawText = new TextDecoder().decode(raw);
      if (rawText.startsWith('</') || rawText === '/>') {
        const open = stack.pop();
        if (open === undefined || open.kind !== kind) {
          throw new MaterializationFailure('FormationFailed');
        }
        spans.push(authority.span(open.start, span.endByte()));
      } else if (rawText !== '>') {
        stack.push({ start: span.startByte(), kind });
      }
    }
  }
  if (stack.length > 0) {
    throw new MaterializationFailure('FormationFailed');
  }
  return spans;
}

function bitsOfFloat64(value: number): bigint {
  const view = new DataView(new ArrayBuffer(8));
  view.setFloat64(0, value, false);
  return view.getBigUint64(0, false);
}

function float64FromBits(bits: bigint): number {
  const view = new DataView(new ArrayBuffer(8));
  view.setBigUint64(0, bits & 0xffffffffffffffffn, false);
  return view.getFloat64(0, false);
}

/** Lowercase hex of one byte sequence (deduplication key material only). */
function hexOf(bytes: Uint8Array): string {
  let out = '';
  for (const byte of bytes) {
    out += byte.toString(16).padStart(2, '0');
  }
  return out;
}
